config/routes.rb
Rails.application.routes.draw do
  #get 'articles/index'
  #get "/articles", to: "articles#index"

  root "articles#index"

  #get "/articles/:id", to: "articles#show"
  resources :articles


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @articles = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<h1>Hello, Rails!</h1>

<h1>Articles</h1>

<ul>
  <% @articles.each do |article| %>
    
    <li>
    <a href="<%= article_path(article) %>">
      <%= article.title %>
     </a>
    </li>
  <% end %>
    
</ul>



<p>Find me in app/views/articles/index.html.erb</p>

app/views/articles/show.html.erb
<h1><%=@articles.title%></h1>
<p><%= @articles.body%> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstBlogRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>